<a href="https://colab.research.google.com/github/AbhishekRReddy/TensforFlow-Learnings/blob/main/00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Outline
* Introduction to tensors.
* Getting information from the tensors.
* Manipulating the tensors.
* Tensors and NumPy
* Using @tf.function (A Way to speed up the regular Python Functions)
* Using the GPUs with TensorFLow (or TPUs)

# Intruduction to Tensors

In [2]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [4]:
# Creating the Tensors with tf.constant()
scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimensions of a tensor (ndim-number of dimension)
scalar.ndim

0

In [7]:
# Create a vector 
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
#Check the dimension of vector
vector.ndim

1

In [9]:
#Create a matrix (Has more than 1 Dimension)
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
#Create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9,]],dtype=tf.float16) #we specify the datatype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [15]:
#Lets create tensor 
tensor=tf.constant([[[1,2,3],[3,5,6]],[[7,8,9],[0,0,0]],[[5,8,1],[0,2,5]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 5, 6]],

       [[7, 8, 9],
        [0, 0, 0]],

       [[5, 8, 1],
        [0, 2, 5]]], dtype=int32)>

In [16]:
tensor.ndim

3

### So far what we have learn is.....

* Scalar : A Single number
* Vector: A number with direction 
* Matrix : A 3 dimensional array of numbers
* Tensor: n-dimensional array of numbers